version: "3.7"

services:

  app:
    image: anntey/sentiment-backend:latest
    container_name: django-gunicorn
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command:
      "gunicorn --access-logfile /var/log/gunicorn-access.log --error-logfile /var/log/gunicorn-error.log --workers=3 --bind=0.0.0.0:8000 MainApp.wsgi:application"
    volumes:
      - ./logs/gunicorn:/var/log

  client:
    image: anntey/sentiment-frontend:latest
    container_name: react-serve
    restart: always
    ports:
      - "3000:3000"
    command:
      "serve -s -l tcp://0.0.0.0:3000 build"
    depends_on:
      - app

  nginx:
    image: nginx:1.17
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      # default directory for virtual host descriptions
      - ./nginx:/etc/nginx/conf.d
      - ./backend/static:static
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - app

